import {createSlice} from '@reduxjs/toolkit';

const initialState = {
  isAuthenticated: false,
  isLoading: true,
  user: {
    email: '',
    phone: '',
    fullName: '',
    role: '',
    avatar: '',
    id: '',
  },
};

export const accountSlice = createSlice({
  name: 'account',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doLoginAction: (state, action) => {
      state.isAuthenticated = true;
      state.isLoading = false;
      state.user = action.payload;
    },
    doLogoutAction: (state, action) => {
      localStorage.removeItem('access_token');
      state.isAuthenticated = false;
      state.user = {
        email: '',
        phone: '',
        fullName: '',
        role: '',
        avatar: '',
        id: '',
      };
    },
    doUpdateUserInfoAction:(state, action) => {
      localStorage.removeItem('access_token');
      state.user.fullName = action.payload.fullName
      state.user.phone = action.payload.phone;
    
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {doLoginAction, doLogoutAction,doUpdateUserInfoAction} = accountSlice.actions;

export default accountSlice.reducer;
